const item = [
  {
    id: 1,
    title: "ಇಡ್ಲಿವಡೆ",
    category: "breakfast",
    price: 25,
    img: "../image/idlivada.jpg",
    desc: `I'm baby woke milskh wolf bitters live blue bootle, freegan copper mug whaever cold-press `,
  },
  {
    id: 2,
    title: "ಬೆಣ್ಣೆದೋಸೆ",
    category: "breakfast",
    price: 45,
    img: "../image/dosa.jpeg",
    desc: `I'm baby woke milskh wolf bitters live blue bootle, freegan copper mug whaever cold-press `,
  },
  {
    id: 3,
    title: "ಪಲಾವ್",
    category: "breakfast",
    price: 30,
    img: "../image/palav.jpg",
    desc: `I'm baby woke milskh wolf bitters live blue bootle, freegan copper mug whaever cold-press `,
  },
  {
    id: 4,
    title: "ಹೋಳಿಗೆ  ಊಟ",
    category: "lunch",
    price: 20,
    img: "../image/holige.jpg",
    desc: `I'm baby woke milskh wolf bitters live blue bootle, freegan copper mug whaever cold-press `,
  },
  {
    id: 5,
    title: "ಜೋಳದ ರೊಟ್ಟಿ",
    category: "lunch",
    price: 20,
    img: "../image/jolada.jpg",
    desc: `I'm baby woke milskh wolf bitters live blue bootle, freegan copper mug whaever cold-press `,
  },
  {
    id: 6,
    title: "ಬೋಂಡಾ ಸೂಪ್",
    category: "breakfast",
    price: 20,
    img: "../image/bonda.jpeg",
    desc: `I'm baby woke milskh wolf bitters live blue bootle, freegan copper mug whaever cold-press `,
  },
  {
    id: 7,
    title: "ಊಟ",
    category: "lunch",
    price: 60,
    img: "../image/annasambar.jpg",
    desc: `I'm baby woke milskh wolf bitters live blue bootle, freegan copper mug whaever cold-press `,
  },
  {
    id: 8,
    title: "ಶೇಂಗಾ ಹೋಳಿಗೆ",
    category: "lunch",
    price: 25,
    img: "../image/shenga.jpg",
    desc: `I'm baby woke milskh wolf bitters live blue bootle, freegan copper mug whaever cold-press `,
  },
  {
    id: 9,
    title: "ಪುರಿ",
    category: "breakfast",
    price:  50,
    img: "../image/puri.jpg",
    desc: `I'm baby woke milskh wolf bitters live blue bootle, freegan copper mug whaever cold-press `,
  },
  {
    id: 10,
    title: "ಮಂಡಕ್ಕಿ ಉಸ್ಲಿ",
    category: "breakfast",
    price: 30,
    img: "../image/mandakki.jpg",
    desc: `I'm baby woke milskh wolf bitters live blue bootle, freegan copper mug whaever cold-press `,
  },
];

export default item;      